### ISSUE TITLE
Use Openstack environment variables

### ISSUE THREAD

**Issue by aurynn** [redhat-cip/swiftbackmeup#28]
Hi

I didn't see this in the README, but, does this use the Openstack environment variables (if they're set), or, only the configuration file values?

If only configuration files, can it use the envars?

**Comment by fcharlier** [comment]
Hi, very sorry for the delay answering.

If the OpenStack credentials are not set in the configuration they will be read from the environment variables.

See the following code:
- https://github.com/redhat-cip/swiftbackmeup/blob/master/swiftbackmeup/configuration.py#L79-L82
- https://github.com/redhat-cip/swiftbackmeup/blob/master/swiftbackmeup/configuration.py#L79-L82
